name: Deploy Lambda

on:
  push:
    branches:
      - dev
      - staging
      - main

permissions:
  id-token: write
  contents: read # Necesario para checkout OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Terraform environment
        run: |
          if [ "${GITHUB_REF_NAME}" = "dev" ]; then
            echo "TF_ENV=DEV" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "staging" ]; then
            echo "TF_ENV=STAGING" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "TF_ENV=PROD" >> $GITHUB_ENV
          else
            echo "Unsupported branch"
            exit 1
          fi

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Package Lambda
        run: |
          cd lambda
          zip -r function.zip lambda_function.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: TERRAFORM/ENVIRONMENT/${{ env.TF_ENV }}
        run: terraform init

      - name: Terraform Validate
        working-directory: TERRAFORM/ENVIRONMENT/${{ env.TF_ENV }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: TERRAFORM/ENVIRONMENT/${{ env.TF_ENV }}
        run: terraform plan

      - name: Terraform Apply
        working-directory: TERRAFORM/ENVIRONMENT/${{ env.TF_ENV }}
        run: terraform apply -auto-approve
